engines:
  rubocop:
    enabled: true
  brakeman:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
ratings:
  paths:
  - bin/**
  - lib/**
exclude_paths:
- Gemfile
- Capfile
- README.md
- Rakefile