AllCops:
  Include:
    - 'Rakefile'
    - 'config.rb'
  Exclude:
    - db/**/**
    - Gemfile
    - Gemfile.lock
  DisplayCopNames: true

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 180
