language: ruby

rvm:
 - '2.3.1'

before_script:
  - cp config/database.example.yml config/database.yml

services:
  - postgresql

addons:
  postgresql: "9.4"
  
script:
  - bundle exec rspec spec/

env:
  global:
    - DEAL_URL=https://api.hubapi.com/deals/v1/deal/recent/modified?
    - CONTACT_URL=https://api.hubapi.com/contacts/v1/lists/all/contacts/all?
    - OWNER_URL=https://api.hubapi.com/owners/v2/owners/?
    - COMPANY_URL=https://api.hubapi.com/companies/v2/companies/recent/modified?
    - ENGAGEMENT_URL=https://api.hubapi.com/engagements/v1/engagements/recent/modified?